import type { Metadata } from "next";
import { Geist, Geist_Mono, Fraunces, Newsreader, Tinos } from "next/font/google";
import "./globals.css";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
});

const tinos = Tinos({
  weight: "400",
  variable: "--font-tinos",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${geistSans.variable} ${geistMono.variable} ${newsreader.variable} ${tinos.variable} h-full antialiased`}
    >
      <body className="max-w-xl mt-40 mx-auto flex flex-col">{children}</body>
    </html>
  );
}
